/**
 * Material shading tables, recovered from the game binary.
 *
 * GENERATED by tools/extract-patterns.mjs -- edit that, not this.
 *
 * A material's colour is its base Color blended toward a tint by
 * `table[y % rows][x % cols] * amount`. Three tables are filled with random
 * values when the game starts rather than shipped, so they are described by
 * size here and generated to match.
 */
export const PATTERNS = {
  "MetallicShavings": [
    [
      0.5,
      1,
      0.75,
      0.5,
      1,
      0.75,
      1,
      0.75,
      0.5
    ],
    [
      1,
      0.75,
      0.5,
      1,
      0.75,
      1,
      0.75,
      0.5,
      0.5
    ],
    [
      0.75,
      0.5,
      1,
      0.75,
      0.5,
      0.75,
      0.5,
      1,
      0.75
    ],
    [
      0.75,
      0.5,
      0.75,
      0.5,
      1,
      0.75,
      1,
      0.75,
      1
    ],
    [
      0.5,
      1,
      0.75,
      1,
      0.75,
      0.5,
      0.75,
      1,
      0.75
    ],
    [
      1,
      0.75,
      0.5,
      0.75,
      0.5,
      1,
      0.75,
      0.75,
      0.5
    ],
    [
      0.75,
      0.5,
      1,
      0.75,
      1,
      0.75,
      0.5,
      1,
      0.75
    ],
    [
      0.5,
      1,
      0.75,
      0.5,
      0.75,
      0.5,
      1,
      0.75,
      0.5
    ],
    [
      1,
      0.75,
      0.5,
      0.5,
      0.5,
      1,
      0.75,
      0.5,
      0.5
    ]
  ],
  "GranitePattern": [
    [
      0.5,
      1,
      1,
      1,
      1,
      0.5
    ],
    [
      0.5,
      1,
      0.5,
      0.5,
      0.5,
      1
    ],
    [
      1,
      0.5,
      1,
      1,
      0.5,
      1
    ],
    [
      1,
      0.5,
      1,
      1,
      0.5,
      1
    ],
    [
      1,
      0.5,
      1,
      0.5,
      0.5,
      1
    ],
    [
      0.5,
      1,
      0.5,
      1,
      1,
      0.5
    ]
  ],
  "CrystalPattern": [
    [
      1,
      1,
      0.8,
      0.25,
      0.25,
      0.25,
      1,
      1,
      0.8
    ],
    [
      0.8,
      0.8,
      0.75,
      0.25,
      0.25,
      1,
      1,
      0.8,
      0.25
    ],
    [
      0.8,
      0.8,
      0.75,
      0.25,
      1,
      1,
      0.8,
      0.25,
      0.25
    ],
    [
      0.8,
      1,
      0.8,
      0.9,
      0.9,
      0.8,
      0.25,
      0.25,
      0.25
    ],
    [
      1,
      0.8,
      0.25,
      0.8,
      0.8,
      0.75,
      0.25,
      0.25,
      1
    ],
    [
      0.8,
      0.25,
      0.25,
      0.8,
      0.8,
      0.75,
      0.25,
      1,
      1
    ],
    [
      0.25,
      0.25,
      0.25,
      1,
      1,
      0.8,
      0.9,
      0.9,
      0.8
    ],
    [
      0.25,
      0.25,
      1,
      1,
      0.8,
      0.25,
      0.8,
      0.8,
      0.75
    ],
    [
      0.25,
      1,
      1,
      0.8,
      0.25,
      0.25,
      0.8,
      0.8,
      0.75
    ]
  ],
  "BarkNoisePattern": [
    [
      0.5,
      1,
      0.75,
      0.5,
      1,
      0.75,
      0.5,
      1,
      0.75
    ],
    [
      1,
      0.9,
      0.8,
      1,
      0.9,
      0.8,
      1,
      0.9,
      0.8
    ],
    [
      1,
      0.8,
      0.5,
      1,
      0.8,
      0.5,
      1,
      0.8,
      0.5
    ],
    [
      1,
      0.75,
      0.5,
      1,
      0.75,
      0.5,
      1,
      0.75,
      0.5
    ],
    [
      1,
      0.75,
      1,
      1,
      0.75,
      1,
      1,
      0.75,
      1
    ],
    [
      0.8,
      1,
      0.9,
      0.7,
      0.4,
      0.7,
      0.8,
      1,
      0.9
    ],
    [
      0.5,
      1,
      0.8,
      0.6,
      0.3,
      0.4,
      0.5,
      1,
      0.8
    ],
    [
      0.5,
      1,
      0.75,
      0.2,
      0.4,
      0.5,
      0.5,
      1,
      0.75
    ],
    [
      0.5,
      1,
      0.75,
      0.5,
      0.6,
      0.4,
      0.5,
      1,
      0.75
    ]
  ]
};

export const RANDOM_PATTERNS = {
  "GravelNoisePattern": {
    "rows": 64,
    "cols": 64,
    "random": true
  },
  "SandNoisePattern": {
    "rows": 64,
    "cols": 64,
    "random": true
  },
  "DirtNoisePattern": {
    "rows": 64,
    "cols": 64,
    "random": true
  }
};

export const DELEGATES = {
  "MetalBits": {
    "builder": "StaticPattern",
    "pattern": "MetallicShavings",
    "tint": "White",
    "amount": 0.9,
    "arg": null,
    "twinkle": null,
    "animated": false
  },
  "Granite": {
    "builder": "StaticPattern",
    "pattern": "GranitePattern",
    "tint": "DarkGray",
    "amount": 0.5,
    "arg": null,
    "twinkle": null,
    "animated": false
  },
  "Crystal": {
    "builder": "StaticPattern",
    "pattern": "CrystalPattern",
    "tint": "White",
    "amount": 0.5,
    "arg": null,
    "twinkle": null,
    "animated": false
  },
  "Gravel": {
    "builder": "StaticPattern",
    "pattern": "GravelNoisePattern",
    "tint": "Black",
    "amount": 0.5,
    "arg": null,
    "twinkle": null,
    "animated": false
  },
  "Sand": {
    "builder": "StaticPattern",
    "pattern": "SandNoisePattern",
    "tint": "White",
    "amount": 0.5,
    "arg": null,
    "twinkle": null,
    "animated": false
  },
  "Dirt": {
    "builder": "StaticPattern",
    "pattern": "DirtNoisePattern",
    "tint": "Black",
    "amount": 0.15,
    "arg": null,
    "twinkle": null,
    "animated": false
  },
  "Bark": {
    "builder": "StaticPattern",
    "pattern": "BarkNoisePattern",
    "tint": "DarkerOrange",
    "amount": 0.25,
    "arg": null,
    "twinkle": null,
    "animated": false
  },
  "Lava": {
    "builder": "OscillatingPattern",
    "pattern": "SandNoisePattern",
    "tint": "Yellow",
    "amount": 0.5,
    "arg": null,
    "twinkle": null,
    "animated": true
  },
  "CheckerPulse": {
    "builder": "CheckerPulse",
    "pattern": null,
    "tint": null,
    "amount": null,
    "arg": 1,
    "twinkle": null,
    "animated": true
  },
  "LeftConveyor": {
    "builder": "Conveyor",
    "pattern": null,
    "tint": null,
    "amount": null,
    "arg": 1,
    "twinkle": null,
    "animated": true
  },
  "RightConveyor": {
    "builder": "Conveyor",
    "pattern": null,
    "tint": null,
    "amount": null,
    "arg": -1,
    "twinkle": null,
    "animated": true
  },
  "Limestone": {
    "builder": "Limestone",
    "pattern": null,
    "tint": null,
    "amount": null,
    "arg": null,
    "twinkle": null,
    "animated": false
  },
  "Sideways": {
    "builder": "Sideways",
    "pattern": null,
    "tint": null,
    "amount": null,
    "arg": null,
    "twinkle": null,
    "animated": false
  },
  "Ruby": {
    "builder": "Twinkle",
    "pattern": null,
    "tint": null,
    "amount": null,
    "twinkle": "Red",
    "animated": true
  },
  "Garnet": {
    "builder": "Twinkle",
    "pattern": null,
    "tint": null,
    "amount": null,
    "twinkle": "Orange",
    "animated": true
  },
  "Topaz": {
    "builder": "Twinkle",
    "pattern": null,
    "tint": null,
    "amount": null,
    "twinkle": "Yellow",
    "animated": true
  },
  "Emerald": {
    "builder": "Twinkle",
    "pattern": null,
    "tint": null,
    "amount": null,
    "twinkle": "Green",
    "animated": true
  },
  "Sapphire": {
    "builder": "Twinkle",
    "pattern": null,
    "tint": null,
    "amount": null,
    "twinkle": "Blue",
    "animated": true
  },
  "Amethyst": {
    "builder": "Twinkle",
    "pattern": null,
    "tint": null,
    "amount": null,
    "twinkle": "Purple",
    "animated": true
  },
  "Diamond": {
    "builder": "Twinkle",
    "pattern": null,
    "tint": null,
    "amount": null,
    "twinkle": "White",
    "animated": true
  },
  "SparklyMetal": {
    "builder": "StaticPattern",
    "pattern": "MetallicShavings",
    "tint": "White",
    "amount": 0.9,
    "arg": null,
    "twinkle": null,
    "animated": true
  }
};
