/**
 * Loops that turn for free, and the member of each that is at fault.
 *
 * GENERATED by tools/find-wheels.mjs -- edit that, not this.
 *
 * A wheel producing material with nothing going in lets a plan mint whatever
 * it likes. Which wheels exist is a property of the game's recipes, not of any
 * question asked of them, so they are found once here rather than rediscovered
 * a solve at a time -- which cost Glass from Granite Gravel eight solves and
 * nine seconds, none of them about silica.
 *
 * Each entry is a whole loop and the material it makes out of nothing. Nothing
 * here is barred: every one of these reactions is a fine reaction, and the
 * solver is told only that this set of them may not be a net source of that
 * material between them. Blaming one member instead took a good recipe off the
 * table everywhere, and moved plans that were not cheating at all.
 *
 * Found by counting whole units: hold every material to net >= 0 with nothing
 * supplied, and any positive total is something made from nothing.
 */
export const FREE_WHEELS = [
  // 4 turning together, making 1 Hydrochloric Acid, 0.5 Chlorine Gas out of nothing
  { material: "Hydrochloric Acid",
    members: [
      "rx:Hydrochloric Acid Dissolves Aluminum",
      "evap:Aluminum Chloride",
      "rx:Chlorine Gas + Hydrogen Gas",
      "rx:Electrolysis of Molten Aluminum Chloride",
    ] },
  // 6 turning together, making 1 Hydrogen Gas, 1 Oxygen Gas out of nothing
  { material: "Hydrogen Gas",
    members: [
      "rx:Expansion of Hydrogen Gas x2",
      "rx:Electrolysis of Water",
      "evap:Ice",
      "chain:cool:Steam#2",
      "burn:Hydrogen Gas (Burning)",
      "ignite:Hydrogen Gas",
    ] },
  // 8 turning together, making 1 Hydrochloric Acid, 1 Molten Salt out of nothing
  { material: "Hydrochloric Acid",
    members: [
      "evap:Magnesium",
      "cond:Molten Manganese",
      "evap:Manganese(II) Chloride",
      "rx:Hydrochloric Acid Dissolves Manganese",
      "rx:Molten Salt + Magnesium Liquid",
      "rx:Chlorine Gas + Hydrogen Gas",
      "rx:Magnesium Chloride Electrolysis",
      "rx:Molten Manganese(II) Chloride Reduction with Sodium",
    ] },
  // 15 turning together, making 1 Hydrogen Gas, 1 Hydrochloric Acid, 1 Hydrofluoric Acid Gas out of nothing
  { material: "Hydrogen Gas",
    members: [
      "rx:Sulfur Trioxide Gas + Steam",
      "rx:Electrolysis of Water",
      "rx:Chlorine Gas + Hydrogen Gas",
      "cond:Hydrofluoric Acid Gas",
      "rx:Quicklime + Hydrochloric Acid",
      "chain:heat:Calcium Chloride#2",
      "cond:Calcium Chloride Vapor",
      "rx:Molten Calcium Chloride + Chlorine Gas",
      "rx:Expansion of Hydrogen Gas x2",
      "rx:Calcium Sulfate Decomposition",
      "rx:Sulfuric Acid + Fluorite",
      "rx:Hydrofluoric Acid Dissolves Calcium",
      "chain:cool:Calcium Vapor#2",
      "evap:Molten Calcium",
      "rx:Hydrogen Combustion",
    ] },
  // 2 turning together, making 0.5 Oxygen Gas out of nothing
  { material: "Oxygen Gas",
    members: [
      "rx:Pyrolusite Decomposition",
      "rx:Manganese (III) Oxide Oxidation",
    ] },
  // 15 turning together, making 1.5 Hydrochloric Acid, 0.5 Sulfuric Acid out of nothing
  { material: "Hydrochloric Acid",
    members: [
      "rx:Sulfur Trioxide Gas + Steam",
      "rx:Chlorine Gas + Hydrogen Gas",
      "chain:cool:Hydrofluoric Acid Gas#2",
      "evap:Hydrofluoric Acid Crystals",
      "rx:Lithium Sulfide + Water",
      "rx:Lithium Hydroxide + Hydrogen Sulfide Gas",
      "rx:Quicklime + Hydrochloric Acid",
      "chain:heat:Calcium Chloride#2",
      "cond:Calcium Chloride Vapor",
      "rx:Molten Calcium Chloride + Chlorine Gas",
      "chain:cool:Calcium Vapor#2",
      "rx:Sulfuric Acid + Fluorite",
      "rx:Calcium Sulfate Decomposition",
      "rx:Hydrofluoric Acid Dissolves Calcium",
      "evap:Molten Calcium",
    ] },
  // 14 turning together, making 1 Salt, 0.5 Hydrogen Gas, 0.5 Chlorine Gas out of nothing
  { material: "Salt",
    members: [
      "rx:Dissolve Salt in Water",
      "rx:Magnesium Chloride Electrolysis",
      "rx:Chlorine Gas + Hydrogen Gas",
      "rx:Sulfur Trioxide Gas + Steam",
      "rx:Sulfuric Acid + Iron Oxide",
      "rx:Hydrochloric Acid Dissolves Iron",
      "rx:Aqueous Iron(II) Sulfate",
      "rx:Iron(II) Hydroxide Production",
      "rx:Iron(II) Hydroxide Decomposition",
      "rx:Hydrochloric Acid Dissolves Magnesium Oxide",
      "rx:Magnesium Sulfate Decomposition",
      "filter:Aqueous Magnesium Sulfate",
      "rx:Aqueous Iron(II) Sulfate + Magnesium",
      "rx:Electrolysis of Seawater",
    ] },
  // 5 turning together, making 1 Hydrogen Gas, 0.5 Oxygen Gas out of nothing
  { material: "Hydrogen Gas",
    members: [
      "filter:Aqueous Potassium Hydroxide",
      "evap:Potassium Hydroxide",
      "chain:cool:Potassium Gas#2",
      "rx:Potassium + Water",
      "rx:Molten Potassium Hydroxide Electrolysis",
    ] },
  // 21 turning together, making 1 Hydrochloric Acid, 0.5 Chlorine Gas, 0.5 Molten Salt out of nothing
  { material: "Hydrochloric Acid",
    members: [
      "rx:Sulfur Trioxide Gas + Steam",
      "rx:Dissolve Salt in Water",
      "rx:Chlorine Gas + Hydrogen Gas",
      "evap:Salt",
      "rx:Magnesium Chloride Electrolysis",
      "chain:heat:Sodium#2",
      "rx:Electrolysis of Carbon Dioxide",
      "rx:Aqueous Iron(II) Sulfate",
      "rx:Sulfuric Acid + Iron Oxide",
      "rx:Iron(II) Hydroxide Decomposition",
      "rx:Hydrochloric Acid Dissolves Iron Wall",
      "rx:Iron(II) Hydroxide Production",
      "BuildsInto:Iron",
      "rx:Aqueous Iron(II) Sulfate + Zinc",
      "rx:Aqueous Zinc Sulfate Evaporation",
      "rx:Zinc Oxide Reduction 2",
      "rx:Zinc Sulfate Decomposition",
      "evap:Magnesium",
      "rx:Molten Salt + Magnesium Liquid",
      "rx:Electrolysis of Seawater",
      "rx:Sodium Vapor + Steam",
    ] },
  // 29 turning together, making 1.444 Hydrochloric Acid, 0.722 Magnesium, 0.611 Carbon Dioxide out of nothing
  { material: "Hydrochloric Acid",
    members: [
      "rx:Chlorine Gas + Hydrogen Gas",
      "rx:Electrolysis of Carbon Dioxide",
      "rx:Magnesium Chloride Electrolysis",
      "rx:Expansion of Hydrogen Gas x2",
      "rx:Electrolysis of Water",
      "rx:Hydrogen Bromide + Water",
      "cond:Hydrogen Bromide Gas",
      "rx:Sulfur Trioxide Gas + Steam",
      "rx:Sodium Bisulfate + Lye",
      "rx:Salt + Sulfuric Acid",
      "rx:Sodium Sulfide + Hydrochloric Acid",
      "rx:Sodium Sulfate Reduction",
      "evap:Salt",
      "rx:Boudouard Equilibrium 726-970K",
      "evap:Solid Chlorine",
      "chain:cool:Chlorine Gas#2",
      "rx:Tungsten Trioxide + Hydrogen Sulfide Gas",
      "rx:Hydrogen Gas + Bromine Gas",
      "rx:Sulfur Dioxide + Oxygen",
      "rx:Electrolysis of Seawater",
      "rx:Molten Salt + Magnesium Liquid",
      "rx:Aqueous Chlorine",
      "rx:Aqueous Bromine Evaporation",
      "rx:Hydrobromic Acid Dissolves Sodium",
      "rx:Aqueous Chlorine + Aqueous Sodium Bromide",
      "evap:Magnesium",
      "rx:Tungsten Disulfide Roasting",
      "rx:Lithium Sulfide + Water",
      "rx:Lithium Hydroxide + Hydrogen Sulfide Gas",
    ] },
  // 6 turning together, making 0.5 Molten Steel, 0.25 Water, 0.25 Carbon out of nothing
  { material: "Molten Steel",
    members: [
      "rx:Electrolysis of Carbon Dioxide",
      "rx:Boudouard Equilibrium 500-725K",
      "rx:Electrolysis of Water",
      "rx:Expansion of Hydrogen Gas x2",
      "rx:Steel Alloy",
      "rx:Molten Steel + Oxygen Gas",
    ] },
  // 6 turning together, making 1.5 Carbon Monoxide, 0.75 Oxygen Gas, 0.5 Hydrogen Gas out of nothing
  { material: "Carbon Monoxide",
    members: [
      "rx:Boudouard Equilibrium 726-970K",
      "rx:Electrolysis of Carbon Dioxide",
      "rx:Antimony(III) Oxide Reduction",
      "rx:Antimony Roasting",
      "rx:Electrolysis of Water",
      "rx:Expansion of Hydrogen Gas x2",
    ] },
  // 14 turning together, making 0.75 Oxygen Gas out of nothing
  { material: "Oxygen Gas",
    members: [
      "chain:cool:Potassium Gas#2",
      "evap:Potassium",
      "evap:Potassium Hydroxide",
      "rx:Electrolysis of Carbon Dioxide",
      "rx:Boudouard Equilibrium 726-970K",
      "rx:Molten Potassium Hydroxide Electrolysis",
      "chain:heat:Sulfur#2",
      "cond:Sulfur Vapor",
      "rx:Molten Potassium + Molten Sulfur",
      "rx:Potassium Oxide + Water",
      "rx:Sulfur Dioxide + Carbon",
      "rx:Expansion of Hydrogen Gas x2",
      "rx:Electrolysis of Water",
      "rx:Potassium Sulfide Decomposition",
    ] },
  // 12 turning together, making 0.75 Lye, 0.5 Chlorine Gas, 0.375 Hydrogen Gas out of nothing
  { material: "Lye",
    members: [
      "rx:Magnesium Chloride Electrolysis",
      "evap:Salt",
      "chain:heat:Magnesium#2",
      "cond:Magnesium Gas",
      "rx:Molten Salt + Magnesium Liquid",
      "rx:Sodium + Steam",
      "rx:Lithium Sulfide + Water",
      "rx:Lithium Hydroxide + Hydrogen Sulfide Gas",
      "rx:Chlorine Gas + Hydrogen Gas",
      "rx:Hydrochloric Acid Dissolves Iron Oxide",
      "rx:Iron(II) Hydroxide Decomposition",
      "rx:Iron(II) Hydroxide Production",
    ] },
  // 10 turning together, making 0.75 Carbon Dioxide, 0.437 Oxygen Gas, 0.375 Hydrogen Gas out of nothing
  { material: "Carbon Dioxide",
    members: [
      "rx:Electrolysis of Carbon Dioxide",
      "rx:Expansion of Hydrogen Gas x2",
      "rx:Electrolysis of Water",
      "chain:heat:Sodium#2",
      "rx:Sodium Carbonate Reduction",
      "rx:Carbonic Acid",
      "rx:Carbonic Acid + Lye",
      "rx:Hydrogen Combustion",
      "rx:Boudouard Equilibrium 500-725K",
      "rx:Sodium Vapor + Steam",
    ] },
  // 17 turning together, making 1.444 Hydrochloric Acid, 0.5 Oxygen Gas, 0.444 Hydrogen Gas out of nothing
  { material: "Hydrochloric Acid",
    members: [
      "rx:Chlorine Gas + Hydrogen Gas",
      "chain:cool:Potassium Gas#2",
      "evap:Potassium Hydroxide",
      "rx:Electrolysis of Carbon Dioxide",
      "evap:Salt",
      "rx:Sulfuric Acid Production",
      "rx:Salt + Sulfuric Acid",
      "rx:Sodium Bisulfate + Lye",
      "rx:Sodium Sulfide + Hydrochloric Acid",
      "rx:Sodium Sulfate Reduction",
      "rx:Boudouard Equilibrium 726-970K",
      "rx:Molten Potassium Hydroxide Electrolysis",
      "rx:Potassium Oxide + Water",
      "rx:Sodium + Steam",
      "rx:Molten Salt Electrolysis",
      "rx:Hydrogen Sulfide Gas + Oxygen Gas",
      "rx:Potassium + Carbon Dioxide",
    ] },
];

/**
 * The pair inside each loop that mints between them, and which to drop.
 *
 * Shaped for `KNOWN_BUGS` in plan-fresh.js, and gated the same way: the pair
 * is re-measured against the data on every build, so an exclusion lifts itself
 * if the recipe is ever fixed. `sole` marks the ones where the half being
 * dropped is the only maker of something, which is a judgement worth a look.
 */
export const MINTING_PAIRS = [
  {
    "drop": "rx:Hydrochloric Acid Dissolves Aluminum",
    "with": "evap:Aluminum Chloride",
    "mints": "H",
    "only": true,
    "verdict": "creates",
    "sole": false,
    "loop": 4,
    "material": "Hydrochloric Acid"
  },
  {
    "drop": "burn:Hydrogen Gas (Burning)",
    "with": "chain:cool:Steam#2",
    "mints": "O",
    "only": true,
    "verdict": "creates",
    "sole": false,
    "loop": 6,
    "material": "Hydrogen Gas"
  },
  {
    "drop": "rx:Hydrochloric Acid Dissolves Manganese",
    "with": "cond:Molten Manganese",
    "mints": "H",
    "only": false,
    "verdict": "creates",
    "sole": false,
    "loop": 8,
    "material": "Hydrochloric Acid"
  },
  {
    "drop": "rx:Quicklime + Hydrochloric Acid",
    "with": "rx:Electrolysis of Water",
    "mints": "Cl",
    "only": false,
    "verdict": "creates",
    "sole": false,
    "loop": 15,
    "material": "Hydrogen Gas"
  },
  {
    "drop": "rx:Pyrolusite Decomposition",
    "with": "rx:Manganese (III) Oxide Oxidation",
    "mints": "O",
    "only": true,
    "verdict": "creates",
    "sole": false,
    "loop": 2,
    "material": "Oxygen Gas"
  },
  {
    "drop": "rx:Quicklime + Hydrochloric Acid",
    "with": "rx:Chlorine Gas + Hydrogen Gas",
    "mints": "H",
    "only": false,
    "verdict": "creates",
    "sole": false,
    "loop": 15,
    "material": "Hydrochloric Acid"
  },
  {
    "drop": "rx:Hydrochloric Acid Dissolves Iron",
    "with": "rx:Chlorine Gas + Hydrogen Gas",
    "mints": "H",
    "only": false,
    "verdict": "creates",
    "sole": false,
    "loop": 14,
    "material": "Salt"
  },
  {
    "drop": "rx:Potassium + Water",
    "with": "filter:Aqueous Potassium Hydroxide",
    "mints": "H",
    "only": false,
    "verdict": "creates",
    "sole": false,
    "loop": 5,
    "material": "Hydrogen Gas"
  },
  {
    "drop": "rx:Aqueous Zinc Sulfate Evaporation",
    "with": "rx:Sulfur Trioxide Gas + Steam",
    "mints": "H",
    "only": false,
    "verdict": "creates",
    "sole": false,
    "loop": 21,
    "material": "Hydrochloric Acid"
  },
  {
    "drop": "rx:Aqueous Bromine Evaporation",
    "with": "rx:Sulfur Trioxide Gas + Steam",
    "mints": "Br",
    "only": false,
    "verdict": "creates",
    "sole": false,
    "loop": 29,
    "material": "Hydrochloric Acid"
  },
  {
    "drop": "rx:Molten Steel + Oxygen Gas",
    "with": "rx:Electrolysis of Carbon Dioxide",
    "mints": "C",
    "only": true,
    "verdict": "creates",
    "sole": false,
    "loop": 6,
    "material": "Molten Steel"
  },
  {
    "drop": "rx:Antimony Roasting",
    "with": "rx:Antimony(III) Oxide Reduction",
    "mints": "O",
    "only": true,
    "verdict": "creates",
    "sole": false,
    "loop": 6,
    "material": "Carbon Monoxide"
  },
  {
    "drop": "rx:Potassium Sulfide Decomposition",
    "with": "rx:Molten Potassium + Molten Sulfur",
    "mints": "O",
    "only": false,
    "verdict": "creates",
    "sole": false,
    "loop": 14,
    "material": "Oxygen Gas"
  },
  {
    "drop": "rx:Molten Salt + Magnesium Liquid",
    "with": "rx:Magnesium Chloride Electrolysis",
    "mints": "Cl",
    "only": false,
    "verdict": "creates",
    "sole": false,
    "loop": 12,
    "material": "Lye"
  },
  {
    "drop": "rx:Sodium Carbonate Reduction",
    "with": "rx:Electrolysis of Carbon Dioxide",
    "mints": "O",
    "only": true,
    "verdict": "creates",
    "sole": false,
    "loop": 10,
    "material": "Carbon Dioxide"
  },
  {
    "drop": "rx:Hydrogen Sulfide Gas + Oxygen Gas",
    "with": "rx:Sulfuric Acid Production",
    "mints": "O",
    "only": false,
    "verdict": "creates",
    "sole": false,
    "loop": 17,
    "material": "Hydrochloric Acid"
  }
];
